AZURE_LOCATION: 'westeurope'
RESOURCE_NAME_PREFIX: 'apimdemoswati'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'github.com/winmike'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'
